config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self) rescue ActiveAdmin::DatabaseHitDuringLoad

  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  authenticate :admin_user do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount_devise_token_auth_for 'User', at: '/api/v1/users', controllers: {
    registrations: 'api/v1/registrations',
    confirmations: 'api/v1/confirmations',
    sessions: 'api/v1/devise_sessions',
    passwords: 'api/v1/passwords'
  }

  root to: 'admin/scheduler#index'

  namespace :api do
    namespace :v1, defaults: { format: :json } do
      namespace :sonar do
        post :webhook
      end
      namespace :stripe do
        post :webhook
      end
      devise_scope :user do
        get :status, to: 'api#status'
        resource :promo_code, only: :show
        resources :legals, only: :show, param: :title
        resources :locations, only: :index do
          get :locations_near_zipcode, on: :collection
        end
        resources :gallery_photos, only: :index
        resources :sessions, only: %i[index show] do
          scope module: :sessions do
            resources :user_sessions, only: %i[create index]
            resource :waitlists, only: %i[create destroy]
            resource :votes, only: %i[create destroy]
          end
        end
        resources :products, only: :index
        resources :user_sessions, only: :index do
          put :cancel
          put :self_check_in, on: :collection
          get :for_self_check_in, on: :collection
        end
        resources :self_check_ins, only: [] do
          get :qr_data, on: :collection
        end
        resources :payments, only: %i[create index] do
          put :create_free_session_intent, on: :collection
        end
        resources :payment_methods, only: %i[create index destroy update]
        resource :user, only: %i[update show] do
          get :profile
          post :resend_confirmation_instructions
          put :update_skill_rating
          post :request_update
          get :referrals
          post :send_membership_handbook
        end
        namespace :sem do
          resources :sessions, only: :show
        end
        resources :session_guests, only: %i[create destroy]
        resources :subscriptions, except: %i[show new edit] do
          member do
            post :reactivate
            post :remove_cancel_at_next_period_end
            post :payment_method, action: :change_payment_method
            put :pause
            put :cancel_pause
            put :unpause
          end
          collection do
            post :request_cancellation
            post :cancel_request_cancellation
            get :preview_prorate
          end
        end
        namespace :active_campaign do
          resources :deals, only: %i[create]
          resources :contacts, only: %i[create]
        end
        namespace :surveys do
          resources :first_timers, only: %i[create]
          resources :sessions, only: %i[create]
        end
      end
    end
  end
end

app/models/subscription_cancellation_request.rb
# == Schema Information
#
# Table name: subscription_cancellation_requests
#
#  id         :bigint           not null, primary key
#  reason     :text
#  user_id    :bigint
#  status     :integer          default("pending")
#  created_at :datetime
#  updated_at :datetime
#
# Indexes
#
#  index_subscription_cancellation_requests_on_status   (status)
#  index_subscription_cancellation_requests_on_user_id  (user_id)
#

class SubscriptionCancellationRequest < ApplicationRecord
  has_paper_trail on: %i[update destroy]

  enum status: {
    pending: 0,
    ignored: 1,
    cancel_at_current_period_end: 2,
    cancel_at_next_month_period_end: 3,
    cancel_immediately: 4,
    cancel_by_user: 5
  }

  belongs_to :user

  delegate :url_helpers, to: 'Rails.application.routes'

  scope :addressed, -> { not_pending }
  scope :for_user, ->(user) { where(user:) }

  def url
    url_helpers.admin_subscription_cancellation_request_url(id, host: ENV.fetch('SERVER_URL', nil))
  end
end

app/views/admin/subscription_cancellation_requests/_actions.html.erb
<% if subscription_cancellation_request.pending? %>
  <% if user.active_subscription %>
    <div>
      <div class="mb-5">
        <div class='mb-2'>
          <label class="font-semibold mr-1">Current membership:</label>
          <%= status_tag 'yes', label: user.membership %>
        </div>
        <div class='mb-2'>
          <label class="font-semibold mr-1">Billing period:</label>
          <span>
            <%= "#{user.active_subscription_current_period_start.to_date} to #{user.active_subscription_current_period_end.to_date}" %>
          </span>
        </div>
        <div class='mb-2'>
          <label class="font-semibold mr-1">Status:</label>
          <span>
            <%= user.active_subscription_status.humanize %>
          </span>
        </div>
        <% unless user.active_subscription_paused? %>
          <div class="mb-2">
            <label class="font-semibold mr-1">Will be paused:</label>
            <%= status_tag user.active_subscription_will_pause? %>
          </div>
        <% end %>
        <div class="mb-2">
          <label class="font-semibold mr-1">Cancel at current period end:</label>
          <%= status_tag user.active_subscription_cancel_at_period_end? %>
        </div>
        <div class="mb-6">
          <label class="font-semibold mr-1">Cancel at next period end:</label>
          <%= status_tag user.active_subscription_cancel_at_next_period_end? %>
        </div>
      </div>
      <%= form_tag(action_admin_subscription_cancellation_request_path) do %>
        <%= button_tag 'Cancel At Current Period End',
                        type: :submit,
                        name: :action_type,
                        value: :cancel_at_current_period_end,
                        class: 'block mb-2 w-64',
                        data: { disable_with: 'Loading...',
                                confirm: 'Are you sure you want to cancel the membership? ' \
                                         'Subscription will be automatically canceled at ' \
                                         'current period end.' } %>
        <%= button_tag 'Cancel At Next Month Period End',
                        type: :submit,
                        name: :action_type,
                        value: :cancel_at_next_month_period_end,
                        class: 'block mb-2 w-64',
                        data: { disable_with: 'Loading...',
                                confirm: 'Are you sure you want to cancel the membership? ' \
                                         'Subscription will be automatically canceled at ' \
                                         'next month period end.' } %>
        <%= button_tag 'Cancel Immediately',
                        type: :submit,
                        name: :action_type,
                        value: :cancel_immediately,
                        class: 'block w-64',
                        data: { disable_with: 'Loading...',
                                confirm: 'Are you sure you want to cancel the membership? ' \
                                         'Subscription will be canceled immediately. User ' \
                                         'credits will be reset to zero and he will not be ' \
                                         'a member anymore.' } %>
      <% end %>
    </div>
  <% else %>
    <%= render 'not_active_subscription', user: user %>
  <% end %>
<% else %>
  <%= render 'not_pending', subscription_cancellation_request: subscription_cancellation_request %>
<% end %>

app/views/admin/subscription_cancellation_requests/_not_active_subscription.html.erb
<div>
  User <%= user.full_name %> does not have an active membership
</div>

app/views/admin/subscription_cancellation_requests/_not_pending.html.erb
<div>
  This request has already been marked as
  <span>
    <%= status_tag 'no', label: subscription_cancellation_request.status, class: 'ml-1' %>
  </span>
</div>