config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self) rescue ActiveAdmin::DatabaseHitDuringLoad

  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  authenticate :admin_user do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount_devise_token_auth_for 'User', at: '/api/v1/users', controllers: {
    registrations: 'api/v1/registrations',
    confirmations: 'api/v1/confirmations',
    sessions: 'api/v1/devise_sessions',
    passwords: 'api/v1/passwords'
  }

  root to: 'admin/scheduler#index'

  namespace :api do
    namespace :v1, defaults: { format: :json } do
      namespace :sonar do
        post :webhook
      end
      namespace :stripe do
        post :webhook
      end
      devise_scope :user do
        get :status, to: 'api#status'
        resource :promo_code, only: :show
        resources :legals, only: :show, param: :title
        resources :locations, only: :index do
          get :locations_near_zipcode, on: :collection
        end
        resources :gallery_photos, only: :index
        resources :sessions, only: %i[index show] do
          scope module: :sessions do
            resources :user_sessions, only: %i[create index]
            resource :waitlists, only: %i[create destroy]
            resource :votes, only: %i[create destroy]
          end
        end
        resources :products, only: :index
        resources :user_sessions, only: :index do
          put :cancel
          put :self_check_in, on: :collection
          get :for_self_check_in, on: :collection
        end
        resources :self_check_ins, only: [] do
          get :qr_data, on: :collection
        end
        resources :payments, only: %i[create index] do
          put :create_free_session_intent, on: :collection
        end
        resources :payment_methods, only: %i[create index destroy update]
        resource :user, only: %i[update show] do
          get :profile
          post :resend_confirmation_instructions
          put :update_skill_rating
          post :request_update
          get :referrals
          post :send_membership_handbook
        end
        namespace :sem do
          resources :sessions, only: :show
        end
        resources :session_guests, only: %i[create destroy]
        resources :subscriptions, except: %i[show new edit] do
          member do
            post :reactivate
            post :remove_cancel_at_next_period_end
            post :payment_method, action: :change_payment_method
            put :pause
            put :cancel_pause
            put :unpause
          end
          collection do
            post :request_cancellation
            post :cancel_request_cancellation
            get :preview_prorate
          end
        end
        namespace :active_campaign do
          resources :deals, only: %i[create]
          resources :contacts, only: %i[create]
        end
        namespace :surveys do
          resources :first_timers, only: %i[create]
          resources :sessions, only: %i[create]
        end
      end
    end
  end
end

app/views/admin/scheduler/_alert_pending_requests.html.erb
<%
  show_pending_subscription_cancellation_requests = pending_subscription_cancellation_requests > 0 && current_admin_user.can?(Permission.ability_resource_name(Permission::MANAGE, SubscriptionCancellationRequest.name))
  show_pending_referral_cash_payments = pending_referral_cash_payments > 0 && current_admin_user.can?(Permission.ability_resource_name(Permission::MANAGE, ReferralCashPayment.name))
  show_pending_user_update_requests = pending_user_update_requests > 0 && current_admin_user.can?(Permission.ability_resource_name(Permission::MANAGE, UserUpdateRequest.name))
%>

<% if show_pending_subscription_cancellation_requests || show_pending_referral_cash_payments || show_pending_user_update_requests %>
  <div class='mb-6'>
    <% if show_pending_subscription_cancellation_requests %>
      <div class='flash flash_warning'>
        There are <%= pending_subscription_cancellation_requests %> pending membership
        cancellation requests to review. Please take some action
        <%= link_to 'here', admin_subscription_cancellation_requests_path %>.
      </div>
    <% end %>

    <% if show_pending_referral_cash_payments %>
      <div class='flash flash_warning'>
        There are <%= pending_referral_cash_payments %> pending referral cash payments
        to review. Please take some action
        <%= link_to 'here', admin_referral_cash_payments_path %>.
      </div>
    <% end %>

    <% if show_pending_user_update_requests %>
      <div class='flash flash_warning'>
        There are <%= pending_user_update_requests %> pending user update requests to review.
        Please take some action <%= link_to 'here', admin_user_update_requests_path %>.
      </div>
    <% end %>
  </div>
<% end %>

app/views/admin/scheduler/_calendar.html.erb
<div id='scheduler-calendar'>
  <%= form_with url: admin_scheduler_path, method: :get, local: true, class: 'mb-5' do %>
    <%= label_tag :location, 'Filter by location:', class: 'mr-2' %>
    <%= select_tag :location,
                  options_from_collection_for_select(locations, 'id', 'name', selected_location.id),
                  include_blank: true,
                  class: 'w-40' %>
    <%= submit_tag 'Filter', class: 'ml-4' %>
  <% end %>

  <%= month_calendar events: sessions do |date, events| %>
    <%
      selected_location_has_notes = selected_location.notes(date).exists?
      filtered_events = events.select do |event|
        validations = event.recurring[:validations]
        next(true) unless validations

        if validations.empty?
          true
        else
          validations[:day].include?(date.wday)
        end
      end.uniq { |e| e.id }.sort_by(&:time)
    %>
    <div class='pb-6'>
      <div class='mb-4'>
        <strong><%= date.day %></strong>
      </div>

      <% if selected_location_has_notes || !date.past? %>
        <div class='flex justify-between items-center bg-gray-300 p-1 mb-4'>
          <div>
            <% if selected_location_has_notes %>
              <%= link_to 'Show Notes', admin_location_notes_path(q: { location_id_eq: selected_location.id,
                                                                       date_eq: date}) %>
            <% end %>
          </div>
          <div>
            <% unless date.past? %>
              <%= link_to 'Add Note',
                          new_admin_location_note_path(location_note: { location_id: selected_location.id,
                                                                        date: }) %>
            <% end %>
          </div>
        </div>
      <% end %>

      <% filtered_events.each do |event| %>
        <div>
          <% if current_admin_user.can?(Permission.ability_resource_name(Permission::MANAGE, Session.name)) %>
            <%= link_to event.title(date), admin_session_path(event.id, date: date) %>
          <% else %>
            <%= event.title(date) %>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>