config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self) rescue ActiveAdmin::DatabaseHitDuringLoad

  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  authenticate :admin_user do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount_devise_token_auth_for 'User', at: '/api/v1/users', controllers: {
    registrations: 'api/v1/registrations',
    confirmations: 'api/v1/confirmations',
    sessions: 'api/v1/devise_sessions',
    passwords: 'api/v1/passwords'
  }

  root to: 'admin/scheduler#index'

  namespace :api do
    namespace :v1, defaults: { format: :json } do
      namespace :sonar do
        post :webhook
      end
      namespace :stripe do
        post :webhook
      end
      devise_scope :user do
        get :status, to: 'api#status'
        resource :promo_code, only: :show
        resources :legals, only: :show, param: :title
        resources :locations, only: :index do
          get :locations_near_zipcode, on: :collection
        end
        resources :gallery_photos, only: :index
        resources :sessions, only: %i[index show] do
          scope module: :sessions do
            resources :user_sessions, only: %i[create index]
            resource :waitlists, only: %i[create destroy]
            resource :votes, only: %i[create destroy]
          end
        end
        resources :products, only: :index
        resources :user_sessions, only: :index do
          put :cancel
          put :self_check_in, on: :collection
          get :for_self_check_in, on: :collection
        end
        resources :self_check_ins, only: [] do
          get :qr_data, on: :collection
        end
        resources :payments, only: %i[create index] do
          put :create_free_session_intent, on: :collection
        end
        resources :payment_methods, only: %i[create index destroy update]
        resource :user, only: %i[update show] do
          get :profile
          post :resend_confirmation_instructions
          put :update_skill_rating
          post :request_update
          get :referrals
          post :send_membership_handbook
        end
        namespace :sem do
          resources :sessions, only: :show
        end
        resources :session_guests, only: %i[create destroy]
        resources :subscriptions, except: %i[show new edit] do
          member do
            post :reactivate
            post :remove_cancel_at_next_period_end
            post :payment_method, action: :change_payment_method
            put :pause
            put :cancel_pause
            put :unpause
          end
          collection do
            post :request_cancellation
            post :cancel_request_cancellation
            get :preview_prorate
          end
        end
        namespace :active_campaign do
          resources :deals, only: %i[create]
          resources :contacts, only: %i[create]
        end
        namespace :surveys do
          resources :first_timers, only: %i[create]
          resources :sessions, only: %i[create]
        end
      end
    end
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                                      :integer          not null, primary key
#  email                                   :string
#  encrypted_password                      :string           default(""), not null
#  reset_password_token                    :string
#  reset_password_sent_at                  :datetime
#  allow_password_change                   :boolean          default(FALSE)
#  remember_created_at                     :datetime
#  sign_in_count                           :integer          default(0), not null
#  current_sign_in_at                      :datetime
#  last_sign_in_at                         :datetime
#  current_sign_in_ip                      :inet
#  last_sign_in_ip                         :inet
#  created_at                              :datetime         not null
#  updated_at                              :datetime         not null
#  provider                                :string           default("email"), not null
#  uid                                     :string           default(""), not null
#  tokens                                  :json
#  confirmation_token                      :string
#  confirmed_at                            :datetime
#  confirmation_sent_at                    :datetime
#  phone_number                            :string
#  credits                                 :integer          default(0), not null
#  is_referee                              :boolean          default(FALSE), not null
#  is_sem                                  :boolean          default(FALSE), not null
#  stripe_id                               :string
#  free_session_state                      :integer          default("not_claimed"), not null
#  free_session_payment_intent             :string
#  first_name                              :string           default(""), not null
#  last_name                               :string           default(""), not null
#  zipcode                                 :string
#  free_session_expiration_date            :date
#  referral_code                           :string
#  subscription_credits                    :integer          default(0), not null
#  skill_rating                            :decimal(2, 1)
#  drop_in_expiration_date                 :date
#  private_access                          :boolean          default(FALSE)
#  active_campaign_id                      :integer
#  birthday                                :date
#  cc_cash                                 :decimal(, )      default(0.0)
#  reserve_team                            :boolean          default(FALSE)
#  instagram_username                      :string
#  first_time_subscription_credits_used_at :datetime
#  subscription_skill_session_credits      :integer          default(0)
#  flagged                                 :boolean          default(FALSE)
#  is_coach                                :boolean          default(FALSE), not null
#  gender                                  :integer
#  bio                                     :string
#  credits_without_expiration              :integer          default(0)
#  scouting_credits                        :integer          default(0)
#  apply_cc_cash_to_subscription           :boolean          default(FALSE)
#  signup_state                            :integer          default("created")
#  work_occupation                         :string
#  work_company                            :string
#  work_industry                           :string
#  links                                   :string           default([]), is an Array
#  utm_source                              :string
#  utm_medium                              :string
#  utm_campaign                            :string
#  utm_term                                :string
#  utm_content                             :string
#
# Indexes
#
#  index_users_on_confirmation_token            (confirmation_token) UNIQUE
#  index_users_on_drop_in_expiration_date       (drop_in_expiration_date)
#  index_users_on_email                         (email) UNIQUE
#  index_users_on_free_session_expiration_date  (free_session_expiration_date)
#  index_users_on_is_coach                      (is_coach)
#  index_users_on_is_referee                    (is_referee)
#  index_users_on_is_sem                        (is_sem)
#  index_users_on_phone_number                  (phone_number) UNIQUE
#  index_users_on_private_access                (private_access)
#  index_users_on_referral_code                 (referral_code) UNIQUE
#  index_users_on_reset_password_token          (reset_password_token) UNIQUE
#  index_users_on_uid_and_provider              (uid,provider) UNIQUE
#  index_users_on_utm_campaign                  (utm_campaign)
#  index_users_on_utm_content                   (utm_content)
#  index_users_on_utm_medium                    (utm_medium)
#  index_users_on_utm_source                    (utm_source)
#  index_users_on_utm_term                      (utm_term)
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  include DeviseTokenAuth::Concerns::User
  include Rails.application.routes.url_helpers

  FREE_SESSION_EXPIRATION_DAYS = 30.days.freeze

  has_paper_trail ignore: %i[sign_in_count
                             current_sign_in_at
                             last_sign_in_at
                             current_sign_in_ip
                             last_sign_in_ip
                             tokens]

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  enum signup_state: {
    created: 0,
    personal_details: 1,
    completed: 2
  }, _prefix: true

  enum free_session_state: {
    not_claimed: 0,
    claimed: 1,
    used: 2,
    expired: 3,
    not_apply: 4
  }, _prefix: :free_session

  enum gender: {
    male: 0,
    female: 1,
    other: 2
  }, _prefix: true

  has_one :last_checked_in_user_session,
          -> { checked_in.order(date: :desc) },
          class_name: 'UserSession',
          inverse_of: :user,
          dependent: :destroy

  has_one :first_future_user_session,
          -> { future.reserved_or_confirmed.order(date: :asc, 'sessions.time' => :asc) },
          class_name: 'UserSession',
          inverse_of: :user,
          dependent: :destroy

  has_one :active_subscription,
          -> { active_or_paused.recent },
          class_name: 'Subscription',
          inverse_of: :user,
          dependent: :destroy

  has_one :default_payment_method,
          -> { where(default: true) },
          class_name: 'PaymentMethod',
          inverse_of: :user,
          dependent: :destroy

  has_one :referral_promo_code,
          class_name: 'PromoCode',
          dependent: :destroy,
          inverse_of: :user

  has_one :last_player_evaluation,
          -> { order(date: :desc, created_at: :desc) },
          class_name: 'PlayerEvaluation',
          inverse_of: :user,
          dependent: nil

  has_many :user_sessions, dependent: :destroy
  has_many :sem_sessions, dependent: :destroy
  has_many :referee_sessions, dependent: :destroy
  has_many :coach_sessions, dependent: :destroy
  has_many :sessions, through: :user_sessions
  has_many :payments, dependent: :nullify
  has_many :subscriptions, dependent: :destroy
  has_many :user_session_waitlists, dependent: :destroy
  has_many :payment_methods, dependent: :destroy
  has_many :player_evaluations, dependent: :destroy
  has_many :user_update_requests, dependent: :destroy
  has_many :late_arrivals, dependent: :destroy
  has_many :session_surveys, dependent: :nullify

  has_one_attached :image, dependent: :destroy do |attachable|
    attachable.variant :thumb, resize_to_limit: [200, 200]
  end

  validates :uid, uniqueness: { scope: :provider }
  validates :password, confirmation: true
  validates :credits, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :subscription_credits, presence: true, numericality: { only_integer: true }
  validates :subscription_skill_session_credits,
            presence: true,
            numericality: { only_integer: true }
  validates :free_session_state, presence: true
  validates :first_name,
            presence: true,
            unless: :signup_state_created?
  validates :last_name,
            presence: true,
            unless: :signup_state_created?
  validates :phone_number, uniqueness: true, allow_nil: true
  validates :phone_number,
            presence: true,
            unless: :signup_state_created?
  validates :gender,
            presence: true,
            unless: :signup_state_created?,
            on: :create
  validates :birthday,
            presence: true,
            unless: :signup_state_created?,
            on: :create
  validates :zipcode,
            presence: true,
            length: { maximum: 5 },
            numericality: { only_integer: true },
            unless: :signup_state_created?
  validates :skill_rating,
            numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 5 },
            allow_nil: true

  scope :referees, -> { where(is_referee: true) }
  scope :sems, -> { where(is_sem: true) }
  scope :coaches, -> { where(is_coach: true) }
  scope :no_credits, -> { where(credits: 0, subscription_credits: 0) }
  scope :sorted_by_full_name, -> { order('LOWER(first_name) ASC, LOWER(last_name) ASC') }
  scope :members, -> { joins(:active_subscription) }
  scope :reserve_team, -> { where(reserve_team: true) }
  scope :employees, -> { referees.or(sems).or(coaches) }

  before_validation :init_uid
  before_save :normalize_instagram_username, :normalize_links
  after_update :update_external_records, :create_referral_code
  after_destroy :delete_stripe_customer, :delete_stripe_promo_code
  after_rollback :delete_stripe_customer, :delete_stripe_promo_code, on: :create

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < Api::V1::ApiUserController
      skip_before_action :authenticate_user!,
                         only: %i[resend_confirmation_instructions send_membership_handbook]

      def show; end

      def profile
        render :show
      end

      def update
        current_user.update!(user_params)
        image = params[:user][:image]

        add_image(image) if image.present?

        render :show
      end

      def update_skill_rating
        skill_rating = skill_rating_params[:skill_rating]

        Users::UpdateSkillRating.call(user: current_user, skill_rating:)

        head :ok
      end

      def request_update
        reason = params[:reason]
        requested_attributes = requested_attributes_params

        Users::UpdateRequest.call(
          user: current_user,
          requested_attributes:,
          reason:
        )

        head :ok
      end

      def resend_confirmation_instructions
        user.send_confirmation_instructions unless user.confirmed?
        head :no_content
      end

      def referrals
        @referrals = Users::GetReferrals.call(user: current_user).list
      end

      def send_membership_handbook
        email = params[:email]

        UserMailer.with(email:).membership_handbook.deliver_later

        head :ok
      end

      private

      def user
        @user ||= User.find_by!(email: params[:email])
      end

      def user_params
        params.require(:user).permit(
          :first_name,
          :last_name,
          :password,
          :password_confirmation,
          :phone_number,
          :zipcode,
          :instagram_username,
          :birthday,
          :gender,
          :apply_cc_cash_to_subscription,
          :bio,
          :signup_state,
          :work_occupation,
          :work_company,
          :work_industry,
          links: []
        )
      end

      def skill_rating_params
        params.require(:user).permit(:skill_rating)
      end

      def requested_attributes_params
        params.permit(:skill_rating)
      end

      def add_image(image)
        AddAttachment.call(
          object: current_user,
          column_name: 'image',
          base_64_attachment: image,
          attachment_name: 'profile_image'
        )
      end
    end
  end
end

app/views/admin/users/_active_subscription_actions.html.erb
<div>
  <% if user.active_subscription_cancel_at_period_end? %>
    <%= button_tag 'Reactivate',
                   type: :submit,
                   name: :action_type,
                   value: :reactivate,
                   data: { disable_with: 'Loading...',
                           confirm: 'Are you sure you want to reactivate the membership?' } %>
  <% elsif user.active_subscription_cancel_at_next_period_end? %>
    <%= button_tag 'Remove Scheduled Cancellation',
                   type: :submit,
                   name: :action_type,
                   value: :remove_scheduled_cancellation,
                   data: { disable_with: 'Loading...',
                           confirm: 'Are you sure you want to remove the membership ' \
                                    'scheduled cancellation?' } %>
  <% elsif user.active_subscription_requested_cancellation? %>
    <div>
      The user has already requested a cancellation.
      Please see the request cancellation
      <%= link_to 'here',
                  admin_subscription_cancellation_requests_path(q: { user_id_eq: user.id }) %>
    </div>
  <% else %>
    <%= button_tag 'Cancel At Current Period End',
                   type: :submit,
                   name: :action_type,
                   value: :cancel_at_period_end,
                   class: 'block mb-2 w-64',
                   data: { disable_with: 'Loading...',
                           confirm: 'Are you sure you want to cancel the membership? ' \
                                    'Subscription will be automatically canceled at ' \
                                    'current period end.' } %>
    <%= button_tag 'Cancel At Next Month Period End',
                   type: :submit,
                   name: :action_type,
                   value: :cancel_at_next_month_period_end,
                   class: 'block mb-2 w-64',
                   data: { disable_with: 'Loading...',
                           confirm: 'Are you sure you want to cancel the membership? ' \
                                    'Subscription will be automatically canceled at ' \
                                    'next month period end.' } %>
    <%= button_tag 'Cancel Immediately',
                   type: :submit,
                   name: :action_type,
                   value: :cancel_immediately,
                   class: 'block w-64',
                   data: { disable_with: 'Loading...',
                           confirm: 'Are you sure you want to cancel the membership? ' \
                                    'Subscription will be canceled immediately. User ' \
                                    'credits will be reset to zero and he will not be ' \
                                    'a member anymore.' } %>
  <% end %>
</div>

app/views/admin/users/_create_or_update_subscription.html.erb
<div>
  <div class='font-semibold mb-3'>
    <%= user.active_subscription ? 'Update' : 'Create' %> Membership
  </div>
  <% if payment_methods.empty? %>
    <p class="inline-block mr-1">User doesn't have any payment method available.</p>
    <%= link_to 'Add payment method',
                new_payment_method_admin_user_path(id: user.id) %>
  <% else %>
    <%
      filtered_products = products.select do |product|
        user.active_subscription ? product.id != user.active_subscription.product_id : true
      end
    %>
    <div class="flex">
      <div class='mr-4'>
        <%= label_tag :product_id, 'Product', class: 'mr-1' %>
        <%= select_tag :product_id,
                       options_for_select(filtered_products.map { |prod| [prod.name, prod.id] }) %>
      </div>
      <div class='mr-4'>
        <%= label_tag :payment_method_id, 'Payment Method', class: 'mr-1' %>
        <%= select_tag :payment_method_id,
                       options_for_select(payment_methods.map { |pm| ["**** #{pm.last_4}", pm.id] }) %>
      </div>
      <div class='mr-4'>
        <%= label_tag :payment_method_id, 'Promo Code', class: 'mr-1' %>
        <%= text_field_tag :promo_code, nil, style: 'width: 100px' %>
      </div>
      <% if user.active_subscription %>
        <%= button_tag 'Update',
                       type: :submit,
                       name: :action_type,
                       value: :update,
                       data: { disable_with: 'Loading...',
                               confirm: 'Are you sure you want to update the membership? ' \
                                        'This may generate additional charges to the user.' } %>
      <% else %>
        <div class='mr-4'>
          <%= label_tag :referral_user_id, 'Referral User', class: 'mr-1' %>
          <%= select_tag :referral_user_id,
                         options_for_select(referral_users.map { |user| [user.full_name, user.id] }),
                         include_blank: true %>
        </div>
        <%= button_tag 'Create',
                       type: :submit,
                       name: :action_type,
                       value: :create,
                       data: { disable_with: 'Loading...',
                               confirm: 'Are you sure you want to create the membership? ' \
                                        'This will charge the user.' } %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/admin/users/_store_items_purchase.html.erb
<%= form_tag(purchase_admin_user_path(user.id), method: :post) do %>
  <div class='mb-5'>
    <%= user.full_name.titleize %>
    has
    <strong>
      <%= "$#{user.cc_cash}" %>
    </strong>
    available from his referral cash
  </div>

  <div class='flex items-center mb-4'>
    <%= check_box_tag :use_cc_cash, true, true, class: 'mr-1' %>
    <%= label_tag :use_cc_cash, 'Spend available CC Cash for purchase' %>
  </div>

  <% store_items.each do |store_item| %>
    <div class='flex items-center mb-3'>
      <div class='mr-4' style='width: 200px'>
        Purchase a <%= store_item.name.downcase %> for
        <strong><%= number_to_currency(store_item.price) %></strong>
      </div>
      <%= button_tag 'Buy',
                     type: :submit, name: :store_item_id, value: store_item.id,
                     data: { disable_with: 'Loading...' } %>
    </div>
  <% end %>
<% end %>

app/views/admin/users/_subscription_information.html.erb
<div class="mb-8">
  <div class='mb-2'>
    <label class="font-semibold mr-1">Current membership:</label>
    <%= status_tag user.active_subscription ? 'yes' : 'no', label: user.membership %>
  </div>
  <% if user.active_subscription %>
    <div class='mb-2'>
      <label class="font-semibold mr-1">Billing period:</label>
      <span>
        <%= "#{user.active_subscription_current_period_start.to_date} to #{user.active_subscription_current_period_end.to_date}" %>
      </span>
    </div>
    <div class='mb-2'>
      <label class="font-semibold mr-1">Status:</label>
      <span>
        <%= user.active_subscription_status.humanize %>
      </span>
    </div>
    <% unless user.active_subscription_paused? %>
      <div class="mb-2">
        <label class="font-semibold mr-1">Will be paused:</label>
        <%= status_tag user.active_subscription_will_pause? %>
      </div>
    <% end %>
    <div class="mb-2">
      <label class="font-semibold mr-1">Cancel at current period end:</label>
      <%= status_tag user.active_subscription_cancel_at_period_end? %>
    </div>
    <div class="mb-2">
      <label class="font-semibold mr-1">Cancel at next period end:</label>
      <%= status_tag user.active_subscription_cancel_at_next_period_end? %>
    </div>
    <div class="mb-6">
      <label class="font-semibold mr-1">Cancel requested:</label>
      <%= status_tag user.active_subscription_requested_cancellation? %>
    </div>
    <%= render 'active_subscription_actions', user: user %>
  <% end %>
</div>

app/views/admin/users/_subscriptions.html.erb
<div>
  <%= form_tag(subscriptions_admin_user_path, method: :post) do %>
    <%= render 'subscription_information', user: user %>
    <%= render 'create_or_update_subscription',
               user: user,
               products: products,
               payment_methods: payment_methods,
               referral_users: referral_users %>
  <% end %>
</div>

app/views/admin/users/new_payment_method.html.erb
<%= form_with url: create_payment_method_admin_user_path(id: @user.id) do %>
  <div class="stripe-error-js hidden bg-red-200 rounded p-2 mb-4"></div>
  <div id="stripe-payment-method" class="max-w-lg mb-5"></div>
  <%= submit_tag 'Add Payment Method' %>
<% end %>